name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install UV
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Set up Python
      run: uv python install 3.11
    
    - name: Install dependencies
      run: make ci-install
    
    - name: Run all checks
      run: |
        echo "Running linting and formatting checks..."
        make ci-lint
        
        echo "Running tests..."
        make ci-test